# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 628233f4b21ef43e454066d6367fc29e790428ad66dc81697b83cbd00eb91a95b81cb5340f0d2c0b994a3e4c52814d1a2c25af0c8bbcc4d6426da8c26daa09e1

test:
  secret_key_base: 73b9ae6f93cd48760dd7aa8a00e98c57f7f327a91c5708e9a567c21fac89ea3017b050bcb8d8e793f4c106c0bade14b65c9ecde75a30dacec62e4d22e131f82b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
